version: '3'


networks:
  kafka:
    ipam:
      driver: default
      config:
        - subnet: "172.22.6.0/24"

services:
  zookepper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-server                        
    restart: unless-stopped                                 
    volumes:                                         
      - "/etc/localtime:/etc/localtime"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:                                          
      - "2181:2181"
    networks:
      kafka:
        ipv4_address: 172.22.6.11

  kafka:
    image: bitnami/kafka:3.4.1
    container_name: kafka                                    
    restart: unless-stopped                                          
    volumes:                                                 
      - "/etc/localtime:/etc/localtime"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookepper:2181                         
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092        
    ports:                              
      - "9092:9092"
    depends_on:                         
      - zookepper
    networks:
      kafka:
        ipv4_address: 172.22.6.12


  kafka-map:
    image: dushixiang/kafka-map:latest
    container_name: kafka-map                            
    restart: unless-stopped                                         
    volumes:
      - "./kafka/kafka-map/data:/usr/local/kafka-map/data"
    environment:
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: 123456
    ports:                              
      - "9006:8080"
    depends_on:                         
      - kafka
    networks:
      kafka:
        ipv4_address: 172.22.6.13
