version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql8                                    
    restart: unless-stopped                                               
    volumes:                                                     
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/data:/var/lib/mysql"
#      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/mysql-files:/var/lib/mysql-files"
    environment:                        
      MYSQL_ROOT_PASSWORD: root         
      MYSQL_DATABASE: demo             
    privileged: true
    user: root
    ports:                            
      - "3308:3306"
