version: '3'

services:
  confluence:
    image: cptactionhank/atlassian-confluence:7.9.3
    container_name: confluence
    restart: always
    volumes:
      - ./app/confluence/logs:/opt/atlassian/confluence/logs
      - ./app/confluence/data:/var/atlassian/confluence
      - ./app/confluence/atlassian-extras-2.4.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/atlassian-extras-decoder-v2-3.4.1.jar
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - db

  db:
    image: postgres:14.5                   
    container_name: confluence-db                                                    
    restart: always

    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      ALLOW_IP_RANGE: 0.0.0.0/0 
    volumes:
      - "./app/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
