version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_5_7                                    
    restart: unless-stopped                                               
    volumes:                                                      
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/init-file.sql:/etc/mysql/init-file.sql"
      - "./mysql/data:/var/lib/mysql"
#      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/log/mysql/error.log:/var/log/mysql/error.log"
      - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d" 
    environment:                       
      MYSQL_ROOT_PASSWORD: root         
      MYSQL_DATABASE: demo              
    ports:                              
      - "7306:3306"
