version: '3'
services:
  redis:
    image: redis:6.0.8                    
    container_name: redis                                                           
    restart: unless-stopped                                                                  
    command: redis-server /etc/redis/redis.conf --requirepass 123456 --appendonly no 
    volumes:                           
      - "./redis/data:/data"
      - "./redis/config/redis.conf:/etc/redis/redis.conf" 
    ports:                              
      - "6379:6379"
